setup:
	go mod init github.com/username/genericmin
	go get golang.org/x/exp/constraints
	go mod tidy

build:
	go build -o genericmin main.go

run:
	go run main.go

clean:
	rm -f genericmin
	rm -f go.mod
	rm -f go.sum
