setup:
	go mod init github.com/username/methodontype
	go get golang.org/x/exp/constraints
	go mod tidy

build:
	go build -o methodontype main.go

run:
	go run main.go

clean:
	rm -f methodontype
	rm -f go.mod
	rm -f go.sum
